### ISSUE TITLE
What should be the dimension of all things?

### ISSUE THREAD

**Issue by ssejal942** [PointMotionInc/Careers#3]
Sir, My doubt is that when I am applying the dimension mentioned in the Figma design, it does not precisely fit my device. So, I am confused about what dimension to use whether according to my device width or according to the dimension given in Figma design.

**Comment by aman-gautam** [comment]
Hi @ssejal942 You can play around with the dimensions to make them work on different device sizes. This will likely have to do more with how you set the width/height of the element rather than the original image sizes.
