### ISSUE TITLE
Error in postman collection - (Testing your server -- Option B)

### ISSUE THREAD

**Issue by anjanKoradia** [PointMotionInc/Careers#4]
I think there is some error in postman collection provided by you to test server.

When i try to test server link provided by you (https://enigmatic-ridge-06779.herokuapp.com) in option-B it dose not clear all the test cases. It failed to clear Sign Up route test cases.

When i try to run entire collection using my server link then also it failed to clear Sign Up route test cases. But when i run separately Sign Up route then it works fine.

**Comment by aman-gautam** [comment]
When I am running the following command, it works perfectly: 

`newman run --env-var baseUrl="https://enigmatic-ridge-06779.herokuapp.com" --env-var username="hakunamatataa" https://raw.githubusercontent.com/UXGorilla/hiring-backend/main/collection.json`

You will need to change  `hakunamatataa` to a unique username each time for this to work.
